services:
  web-app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./recipe_app:/recipe_app
    environment:
      - DB_HOST=database
      - DB_NAME=db_name
      - DB_USER=db_user
      - DB_PASS=pass

    command: >
      sh -c "python manage.py runserver localhost:8000"

    depends_on:
      - database

  database:
    image: postgres:14.6-alpine
    environment:
      - POSTGRES_DB=db_name
      - POSTGRES_USER=db_user
      - POSTGRES_PASSWORD=pass