# Generated by Django 3.0 on 2024-01-28 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'verbose_name': 'Рецепт', 'verbose_name_plural': 'Рецепты'},
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=250, unique=True, verbose_name='Название продукта'),
        ),
        migrations.AlterField(
            model_name='product',
            name='usages',
            field=models.IntegerField(default=0, verbose_name='Кол-во использований в блюдах'),
        ),
        migrations.AlterField(
            model_name='weight',
            name='weight',
            field=models.FloatField(verbose_name='Вес ингредиента в рецепте'),
        ),
    ]
